services:
  db:
    image: postgres:16
    container_name: steam_db
    environment:
      POSTGRES_USER: steam
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: steam_market
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: